name: Auto update pif.json

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-pif:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run pif.py
        run: python3 pif.py

      - name: Commit and push changes (pif.json)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          if ! git diff --quiet; then
            git add pif.json
            git commit -m "Auto update pif.json [CI]"
            git push
          else
            echo "No changes in pif.json"
          fi
